### ISSUE TITLE
Edit version

### ISSUE THREAD

**Issue by humphreyja** [MSUM-ACM/Constitution#1]
It would to have a raw (doc) version of this for future edits.  I will consider converting to doc and adding a sub folder for this.

**Comment by DKMudrechenko** [comment]
Before any edits to the constitution are made they must be voted on, which is not going to happen anytime before the second meeting in Fall 2015. So there is no point to have an open issue for it now,

**Comment by humphreyja** [comment]
Yes we will bring them up at the beginning of the semester.

On Mon, Jun 01, 2015 at 3:32 PM, Dmitrii Mudrechenko < notifications@github.com [notifications@github.com] > wrote:
Before any edits to the constitution are made they must be voted on, which is
not going to happen anytime before the second meeting in Fall 2015. So there is
no point to have an open issue for it now,

—
Reply to this email directly or view it on GitHub
[https://github.com/MSUM-ACM/Constitution/issues/1#issuecomment-107698282] .[https://github.com/notifications/beacon/AGoBr69xp8FQR6jwM6wICSe4RKcqCA6fks5oPLiogaJpZM4Es6Sp.gif]

**Comment by HEFFRo** [comment]
I sent an email about this already but there is not point for a doc form because the constitution only gets revised every 5 years and it is A VERY LONG/HARD process to change anything and really to be honest very unnecessary to challenging related to rules and previous officers. Any changes to the ACM can be done without the constitution. If you think there is a change needed you think then you have to propose it at a meeting, that meets quorum related to the current member status, and be voted on to be sent out to the list serve for all students (current and previous) to see. Then must be formalized and voted on again to make this change effective. If you do think of something that important that needs to be in there I would be surprised non the least because it took us 5 years to go from CIO to President and that was a HUGE CHANGE LOL.

**Comment by humphreyja** [comment]
I've read it through so I can understand how it can be difficult to change. I've
been thinking about optimizing the github and have been throwing around ideas
for a while now.

To be honest I actually don't mind how Anthony packaged a bunch of the old repos
into an archive just to clean it up a bit(it can get a bit overwhelming
otherwise). He should have talked to me before messing with the website one cuz
as of right now we don't have one and I haven't had internet at my new place yet
fml haha. I still think some changes should be changed around but I've put that
on hold for the time being until we can talk to everyone about it. Nothing that
breaks constitution lol.

On Thu, Jun 04, 2015 at 2:44 AM, Jeff McNertney < notifications@github.com [notifications@github.com] > wrote:
I sent an email about this already but there is not point for a doc form because
the constitution only gets revised every 5 years and it is A VERY LONG/HARD
process to change anything and really to be honest very unnecessary to
challenging related to rules and previous officers. Any changes to the ACM can
be done without the constitution. If you think there is a change needed you
think then you have to propose it at a meeting, that meets quorum related to the
current member status, and be voted on to be sent out to the list serve for all
students (current and previous) to see. Then must be formalized and voted on
again to make this change effective. If you do think of something that important
that needs to be in there I would be surprised non the least because it took us
5 years to go from CIO to President and that was a HUGE CHANGE LOL.

—
Reply to this email directly or view it on GitHub
[https://github.com/MSUM-ACM/Constitution/issues/1#issuecomment-108767974] .[https://github.com/notifications/beacon/AGoBrx3W92MSQSz9eJwkStHv3LDhudp9ks5oP_lZgaJpZM4Es6Sp.gif]

**Comment by HEFFRo** [comment]
I thought that was a good idea as well for the archiving but I was more talking about the removing of members and so forth lol! But whatever you guys want to do with the website (Currently which we dont have and need back before school I would say starts haha) is up to you and thats why we left it out cause then you dont have rules mandating what you do or dont do like we had before. Yeah anything new send out a group email because I check mine all day everyday when I do have internet :)
